name: TMP Testing repository dispatch

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/github/primer/dispatches \
             -f "event_type=test-dispatch-receiver"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
