name: TMP Testing repository dispatch

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      # from .github/workflows/add_to_inbox.yml
      - id: get-github-access-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_ID_FOR_GITHUB }}
          private-key: ${{ secrets.PRIMER_ISSUE_TRIAGE_APP_PRIVATE_KEY_FOR_GITHUB }}
          client-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_CLIENT_ID_FOR_GITHUB }}
          client-secret: ${{ secrets.PRIMER_ISSUE_TRIAGE_APP_CLIENT_SECRET_FOR_GITHUB }}
          installation-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_INSTALLATION_ID_FOR_GITHUB }}
      - name: trigger workflow
        run: |
          gh api /repos/github/primer/dispatches -f event_type="test-dispatch-receiver"
        env:
          GH_TOKEN: ${{ steps.get-github-access-token.outputs.access-token }}
